### ISSUE TITLE
Intrepreter chockes on BOM encoded UTF-8 script files. (was Http Support?)

### ISSUE THREAD

**Issue by noxomix** [AmokHuginnsson/huginn#2]
Hey,

Does Huginn has a way to create a http-server? Or Socket-Server?

:)

**Comment by AmokHuginnsson** [comment]
Hello.

No, at this point `Network` package has only client sockets.
Server side sockets are almost useless without proper dispatching mechanism which is yet to be designed.

Thank you for interest.

**Comment by noxomix** [comment]
okay thanks. 
Is there any easy description how to add/create own third-party Extensions/modules? Or is the Difficult-Level to height for a Nodejs self-learning dev like mee ^^ 

Otherways thanks allot 


Edit:

And whats about running Huginn in Windows (10) ? Thats not recommendet yet right?

**Comment by AmokHuginnsson** [comment]
Hello.

There is no explicit documentation on topics you mentioned but there are examples:
- https://github.com/AmokHuginnsson/tress/blob/master/data/huginn_greeter.cxx - for C++ packages
- https://github.com/AmokHuginnsson/huginn/tree/master/packages - for Huginn native packages

Later has the same difficulty level as just writing scripts in Huginn while former additionally requires C++ skills and reading through language implementation enough to understand data types and internal VM interfaces.

[Windows 10](https://codestation.org/windows/) target is build on every commit and extensive test suite is also executed but personally I do not work on Windows platform daily so I do not guarantee the experience.

I hope this helps.

**Comment by noxomix** [comment]
Thaks :)

Edit:

Hm when I try to run a Huginn file, this error comes up? My File ist in UTF-8 formatted but when I try to run it: ``huginn --no-argv .\index.hgn`` this error comes: ```Invalid UTF-8 tail sequence at: 14Invalid UTF-8 tail sequence at: 14Invalid UTF-8 tail sequence at: 14Invalid UTF-8 tail sequence at: 14```

**Comment by AmokHuginnsson** [comment]
Can you attach your script here (the file itself)?

**Comment by noxomix** [comment]
Github doesnt support the .hgn Files :/

**Comment by noxomix** [comment]
But its the ``main(){}`` example programm in the File

**Comment by noxomix** [comment]
I've installed Huginn know on my Debian VPS - but there he dont run anything if I enter "huginn" in the shell this comes up:
![grafik](https://user-images.githubusercontent.com/42320700/99902799-b95aa300-2cc0-11eb-8324-d53d219b4901.png)

**Comment by AmokHuginnsson** [comment]
Yes, you cannot run Huginn as root, please run it as normal (non-root) user.

Did you download `main(){}` example as file or created is locally? (Huginn does not support BOM files.)

**Comment by noxomix** [comment]
Ahh okay I've created manually a .txt File and renamed it to main.hgn in Windows. 

So in Debian it works for now with other user thx

**Comment by noxomix** [comment]
![grafik](https://user-images.githubusercontent.com/42320700/99903012-dcd21d80-2cc1-11eb-9344-b01ea4146501.png)

So in windows I downloadet now the 100doors example, and then the firstline is "error" so I think the windows File system is the problem , I use my Debian VPS yet

**Comment by AmokHuginnsson** [comment]
Did you build Huginn by yourself or did you install it with the installer I provided? By the way did you by any chance install also `yaal-*.msi` package?

**Comment by noxomix** [comment]
Ive installed first the yaal..msi Package - and then the huginn...msi package ,, but the Folder I haven't downloaded 
![grafik](https://user-images.githubusercontent.com/42320700/99903109-95985c80-2cc2-11eb-9914-e50acece3841.png)

**Comment by AmokHuginnsson** [comment]
`yaal` package is used only for development of `huginn.exe` (this specific executable) features and should not be installed otherwise.

**Comment by noxomix** [comment]
So I shouild be uninstall yaal ??

**Comment by AmokHuginnsson** [comment]
Yes.

**Comment by noxomix** [comment]
After I uninstalled yaal then huginn and reinstall huginn the error is the same ``UTF-8 blablabla...`` so I use my VPS then for development. 

So thank you for help

Edit: Is there no way to delete the BOM by compiler/interpreter reading the textfile (.hgn) I think that's the easiest way but for now I don't need it.

**Comment by AmokHuginnsson** [comment]
I just installed the same package on my Windows VM and I cannot reproduce the UTF-8 issue with `100doors.hgn` downloaded directly from https://huginn.org/ site.

Yes. BOM stripping will be implemented.
[edit]
After further consideration BOMs are banned in Huginn scripts by language spec.

**Comment by noxomix** [comment]
Hm then its evetually beacause the Folder where the 100doors.hgn is opened in Virtsual Studio Code hm

edit: nope that's not the Problem so its unimportant for now because windows is ...windows

**Comment by noxomix** [comment]
Next Question: where is the "Network" Package loacted in Github??

**Comment by AmokHuginnsson** [comment]
https://github.com/AmokHuginnsson/yaal/blob/master/tools/huginn/network.cxx

**Comment by noxomix** [comment]
I close this issue now. (and reopen another for next question ^^)

**Comment by AmokHuginnsson** [comment]
**Huginn** requires for scripts to be UTF-8 encoded and **without** BOM markers.
